### ISSUE TITLE
uri type fields don't export URL data

### ISSUE THREAD

**Issue by btinker** [lauraleif/Export#1]
Some items with "type": "uri" do not export URLs because there is no @value key but instead it uses @id key.  
exports empty field:
"pa:relurl": [
        {
            "type": "uri",
            "property_id": 223,
            "property_label": "Related Website",
            "is_public": true,
            "@id": "http:\/\/...\/"
        }
    ],

**Comment by lauraleif** [comment]
The CSV file should contain the full API response for an item in the last column and the full media response in the media:full column. 
Would you be able to send a link to an example item with this issue and/or the full API response from the last column of the exported CSV file to help troubleshoot?

**Comment by lauraleif** [comment]
The latest release (1.2) contains an update to include uri types in the properties field.
