### ISSUE TITLE
Crashes Omeka 2

### ISSUE THREAD

**Issue by brimwats** [lauraleif/Export#2]
Once placed in module directory of Omeka S 2.0, it breaks the omeka install and returns "Omeka S has encountered an error"

**Comment by lauraleif** [comment]
Sorry you experienced this issue - please see if the latest version (1.4.0) fixes this issue for you. It has been tested on Omeka 2.0.1 and seems to work, so if you're still seeing the same error message, please reply with configuration details and/or check your logs to see if there is any additional information there.

**Comment by brimwats** [comment]
Thank you! it works great now :)
