### ISSUE TITLE
Warning:  array_key_exists() expects parameter 2 to be array

### ISSUE THREAD

**Issue by fackrellj** [lauraleif/Export#6]
I started looking into this issue after the posts made in the forum here: https://forum.omeka.org/t/export-module-error-in-csv/13548 and here https://forum.omeka.org/t/native-csv-export/13903

It appears that items with a class (e.g Collection, Event, Dataset, etc.) set are causing this error to be thrown in this section of the code because $single is not always an array: 

Export/view/export/index/download.phtml
![image](https://user-images.githubusercontent.com/75277580/130292070-0443f196-592a-4f59-940e-63465041b816.png)

**Comment by gtnbssn** [comment]
Following this issue as we are affected as well.

**Comment by jonfackrell** [comment]
> Following this issue as we are affected as well.

@gtnbssn I created a pull request to fix this issue, but I haven't heard anything from @lauraleif yet

**Comment by gtnbssn** [comment]
It's working now! Thanks!
